### ISSUE TITLE
Add more information to 'Deployment's in OpenShift generator

### ISSUE THREAD

**Issue by PouriaSterling** [agiledigital/toolform#34]
Currently, toolform is missing functionality to output the `strategy` and `triggers` blocks in **spec**, and also the `envFrom`, `args`, or `readinessProbe` blocks in **spec>template>spec>containers** of the `Deployment` sections of the generated OpenShift deployment file. 

To illustrate, toolform currently produces deployments with the following sections:
```
apiVersion:
kind:
metadata:
  annotations:
    source.path:
    project.artefact:
  name:
spec:
  replicas:
  template:
    metadata:
      labels:
        component:
    spec:
      containers:
      -
        image:
        name:
        imagePullPolicy:
        ports:
          - containerPort:
        volumeMounts:
          - name:
            mountPath:
      volumes:
        - name:
          persistentVolumeClaim:
            claimName:
```
And the goal is to produce the following (asterisks indicate the missing lines):
```
apiVersion:
kind:
metadata:
  annotations:
    source.path:
    project.artefact:
  name:
spec:                           
  strategy:                      *
    type:                        *
  replicas:
  triggers:                      *
    - type:                      *
    - type:                      *
      imageChangeParams:         *
        automatic:               *
        containerNames:          *
        - public:                *
        from:                    *
          kind:                  *
          name:                  *
  template:
    metadata:
      labels:
        component:
    spec:
      containers:
      -

        image:
        name:
        imagePullPolicy:
        envFrom:                 *
        - configMapRef:          *
            name:                *
        ports:
          - containerPort:
        args:                    *
        -                        *
        readinessProbe:          *
          httpGet:               *
            path:                *
            port:                *
          initialDelaySeconds:   *  
          timeoutSeconds:        *
        volumeMounts:
          - name:
            mountPath:
      volumes:
        - name:
          persistentVolumeClaim:
            claimName:
```
